baseurl = "https://mrschyzo.github.io/about-me"
title = "Mr.Schyzo"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

[markup.highlight]
style = "github-dark"

[params]
author = "Marco Catapano"
info = "Software Engineer II @ Trade Republic GmbH"
description = "Mr.Schyzo personal website"
keywords = "blog,developer,personal"
favicon_32 = "/img/favicon-32x32.png"
favicon_16 = "/img/favicon-16x16.png"

since = 2023

enableTwemoji = true

colorScheme = "auto"
hidecolorschemetoggle = false

# customCSS = ["css/custom.css"]
# customSCSS = ["scss/custom.scss"]
# customJS = ["js/custom.js"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 1
url = "https://github.com/mrschyzo/"
[[params.social]]
name = "Linkedin"
icon = "fa fa-linkedin fa-2x"
weight = 3
url = "https://www.linkedin.com/in/marco-catapano/"

# Menu links
[[menu.main]]
name = "About"
weight = 1
url = "about/"
[[menu.main]]
name = "Posts"
weight = 2
url  = "posts/"
