name: Update CV - PR

on:
  push:
    branches: ["master"]
    paths:
      - "cv/**"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "update"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup dependencies
        run: "sudo apt update && sudo apt install -y xfonts-75dpi xfonts-base"
      - name: Install gomplate
        run: "curl -L --fail -o gomplate https://github.com/hairyhenderson/gomplate/releases/download/v3.11.4/gomplate_linux-amd64"
      - name: Make gomplate executable
        run: "chmod +x gomplate"
      - name: Download wkhtmltopdf package
        run: "curl -L --fail -o wkhtmltopdf.deb https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb"
      - name: Install wkhtmltopdf
        run: "sudo dpkg --force-confold -i wkhtmltopdf.deb && rm -f wkhtmltopdf.deb"
      - name: Generate CV
        run: >
          ls -halt ${{ steps.pwd.outputs.out }} ;
          pushd cv ;
          ../gomplate -f handmade-template.html -o cv.html -d data=data.yaml && \
          ../wkhtmltopdf cv.html cv.pdf && \
          mv cv.* ../content/static/cv/ && \
          popd
      - name: Remove unwanted executable
        run: rm -f gomplate
      - name: Check meaningful changes in content
        id: change
        run: |
          if [ -n "$(git status -s content/static/cv/)" ] ; then
            echo "presence=true" | tee $GITHUB_OUTPUT
          else
            echo "No meaningful edits"
          fi
      - name: Pull Request
        if: ${{ steps.change.outputs.presence == 'true' }}
        uses: peter-evans/create-pull-request@v4
        with:
          branch: bot/cv-update
          title:          "[Automatic PR] Update CV in static content"
          commit-message: "Update CV in static content"
          delete-branch: true
          labels: patch
